services:
  # --- Infrastructure ---
  
  api-gateway:
    build:
      context: ../Cyber-Suite-API-Gateway
      dockerfile: Dockerfile
    container_name: cyber-suite-api-gateway
    restart: unless-stopped
    ports:
      - "3001:3000"
    env_file:
      - ./env/api-gateway/.env
    networks:
      - cyber-net

  dashboard:
    build:
      context: ../Cyber-Suite-Dashboard
      dockerfile: Dockerfile.dev
    container_name: cyber-suite-dashboard
    restart: unless-stopped
    env_file:
      - ./env/dashboard/.env
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway
    networks:
      - cyber-net



  # --- Misconfig Checker Services ---

  misconfig-checker:
    build: .
    container_name: misconfig-checker
    restart: unless-stopped
    ports:
      - "8003:8003"
    env_file:
      - ./env/misconfig-service/.env
    depends_on:
      - metasploit
    networks:
      - cyber-net

  metasploit:
    image: metasploitframework/metasploit-framework
    container_name: metasploit
    restart: unless-stopped
    ports:
      - "55553:55553"
    environment:
      - MSF_DATABASE_CONFIG=/usr/share/metasploit-framework/config/database.yml
    env_file:
      - ./env/misconfig-service/.env
    entrypoint: /usr/src/metasploit-framework/msfrpcd
    command: -P ${MSF_PASSWORD} -p 55553 -n -f -a 0.0.0.0
    networks:
      - cyber-net

networks:
  cyber-net:
    driver: bridge
