
# resume information
resume-index = 873698
seed = 7619638348702609062
rate = 10000     
shard = 1/1
nocapture = servername


adapter-ip = 172.27.25.44
# TARGET SELECTION (IP, PORTS, EXCLUDES)
ports = 80,8000-8100
range = 10.0.0.0/8

